package main.java.com.github.return5.r5jlox.token;

public enum TokenType {
    LEFT_PAREN,RIGHT_PAREN,LEFT_BRACE,RIGHT_BRACE,
    COMMA,DOT,MINUS,PLUS,SEMICOLON,SLASH,STAR,PARENT,
    BANG,BANG_EQUAL,EQUAL,EQUAL_EQUAL,GREATER,GREATER_EQUAL,CONCAT,AND,OR,
    LESS,LESS_EQUAL,IDENTIFIER,STRING,NUMBER,DESIGNATION,ELSE,FALSE,FUNCTI,
    FOR,IF,NIL,SAY,RETURN,SUPER,SELF,TRUE,STASH,WHILE,EOF
}
